export const LOAD_ALL_ITEMS = 'LOAD_ALL_ITEMS';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const SELECT_ITEM = 'SELECT_ITEM';
export const DESELECT_ITEM = 'DESELECT_ITEM';

export const TOGGLE_ADD_ITEM = 'TOGGLE_ADD_ITEM';
export const TOGGLE_EDIT_LABOR_PRICE = 'TOGGLE_EDIT_LABOR_PRICE';

export const TOGGLE_ALERT_WINDOW = 'TOGGLE_ALERT_WINDOW';
export const DISPLAY_ALERT = 'DISPLAY_ALERT';

export const TOGGLE_GOLD_AGE_WINDOW = 'TOGGLE_GOLD_AGE_WINDOW';
