const lang = {
    appName: "Quản Lý Tiệm Vàng",
    currency: "VND",
    weightUnit: "Chỉ",

    search: "Tìm Kiếm",
    select: "Chọn",
    remove: "Xoá",
    complete: "Hoàn Tất",
    cancel: "Huỷ Thao Tác",
    selected: "Đã Chọn",
    cart: "Sản Phẩm Đã Chọn",

    alert: "Thông Báo",

    itemName: "Tên Sản Phẩm",
    name: "Tên",
    itemCode: "Mã Sản Phẩm",
    code: "Mã",
    goldAge: "Tuổi Vàng",
    age: "Tuổi",
    itemWeight: "T.L Sản Phẩm",
    stoneWeight: "T.L Đá",
    goldWeight: "T.L Vàng",
    weight: "Trọng Lượng",
    price: "Giá",
    buyIn: "Mua Vào",
    buyGoldPrice: "Giá Vàng Mua Vào",
    buyLaborPrice: "Tiền Công Gốc",
    buyPrice: "Giá Mua",
    buyDate: "Ngày Mua",
    sellOut: "Bán Ra",
    goldPrice: "Giá Vàng",
    laborPrice: "Tiền Công",
    sellPrice: "Giá Bán",
    sellDate: "Ngày Bán",
    priceDifference: "Chênh Lệch",
    laborPriceDifference: "Chênh Lệch Tiền Công",
    date: "Ngày",
    total: "Tổng",

    editLaborPrice: "Thay Đổi Tiền Công",
    addTodaysPrice: "Nhập Giá Vàng",
    addNewItem: "Thêm Sản Phẩm",
    close: "Đóng",

    goldAgeInfo: " Thông Tin Tuổi Vàng",
    oldPrice: "Giá Cũ",
    todaysPrice: "Giá Hôm Nay",
}

module.exports = lang;
